POST http://localhost:3000/api/products
Content-Type: application/json 

{
    "title":"Labtop",
     "description":"habout this product",
    "price":6000
    
}


###////////////////////////////////

GET  http://localhost:3000/api/products


###////////////////////////////////
GET  http://localhost:3000/api/products/1


###////////////////////////////////
PUT http://localhost:3000/api/products/1
Content-Type: application/json 

{
    "title":"updated test"
}


###////////////////////////////////
DELETE  http://localhost:3000/api/products/1
